// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc-jC3OgOgY5kn-rfB25veHJVm6B4IR2U',
    appId: '1:427836812978:web:c9024ed6da3a1bcc38e3ab',
    messagingSenderId: '427836812978',
    projectId: 'todo-today-74b74',
    authDomain: 'todo-today-74b74.firebaseapp.com',
    storageBucket: 'todo-today-74b74.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6FqFjjD9qg5TqAIRu3t5TXUrkTLeeCMc',
    appId: '1:427836812978:android:3ee7d68bb4321c6b38e3ab',
    messagingSenderId: '427836812978',
    projectId: 'todo-today-74b74',
    storageBucket: 'todo-today-74b74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK98LacaCGQ4P90eiTGbKHdPB8CaDIi0w',
    appId: '1:427836812978:ios:952eeb92edb95d4e38e3ab',
    messagingSenderId: '427836812978',
    projectId: 'todo-today-74b74',
    storageBucket: 'todo-today-74b74.appspot.com',
    iosClientId:
        '427836812978-n0tjqtkmh0e5nls863vo3enng26l8es0.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoToday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK98LacaCGQ4P90eiTGbKHdPB8CaDIi0w',
    appId: '1:427836812978:ios:952eeb92edb95d4e38e3ab',
    messagingSenderId: '427836812978',
    projectId: 'todo-today-74b74',
    storageBucket: 'todo-today-74b74.appspot.com',
    iosClientId:
        '427836812978-n0tjqtkmh0e5nls863vo3enng26l8es0.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoToday',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc-jC3OgOgY5kn-rfB25veHJVm6B4IR2U',
    appId: '1:427836812978:web:c9024ed6da3a1bcc38e3ab',
    messagingSenderId: '427836812978',
    projectId: 'todo-today-74b74',
    authDomain: 'todo-today-74b74.firebaseapp.com',
    storageBucket: 'todo-today-74b74.appspot.com',
  );
}
